### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by RustoMCSpit** [shriramters/chordcat#10]

**Comment by shriramters** [comment]
Hi @RustoMCSpit 

Thank you so much for raising this issue and thanks for using Chordcat

I wanted to let you know that I have started working on flatpak support and I have also got it to build with flatpak-builder

You can check the progress here: https://github.com/flathub/flathub/pull/5764


I will close this issue once it is uploaded to flathub

**Comment by shriramters** [comment]
@RustoMCSpit, 
You can now [download chordcat from flathub](https://flathub.org/apps/dev.ters.Chordcat)

I am closing this issue now. 

Thank you!
